#live_config_reload = true
#https://gist.github.com/yoonhoGo/61ea18476a127f5db7b86471ee027876

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.7

[window.padding]
x = 9
y = 9


